name: Secureframe Policy Minder

on:
  workflow_dispatch:
  schedule:
    # evrey Tuesday
    - cron: '0 0 * * 2'

jobs:
  secureframe-policy-minder:
    runs-on: ubuntu-latest
    steps:
      - name: clone secureframe-policy-minder
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: chainguard-dev/secureframe-policy-minder
          path: secureframe-policy-minder
      - name: setup go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: stable
          check-latest: true
      - name: send notifications
        env:
          SLACK_TOKEN: ${{ secrets.POLICY_MINDER_SLACK_TOKEN }}
          SECUREFRAME_TOKEN: ${{ secrets.SECUREFRAME_TOKEN }}
        run: go run .
        working-directory: secureframe-policy-minder
